export { default as Navbar } from "./Navbar/Navbar";
export { default as Header } from "./Header/Header";
export { default as Destinations } from "./Destinations/Destinations";
export { default as Services } from "./Services/Services";
export { default as BookTrip } from "./BookTrip/BookTrip";
export { default as Testimonials } from "./Testimonials/Testimonials";
export { default as Partners } from "./Partners/Partners";
export { default as Subscription } from "./Subscription/Subscription";
export { default as Footer } from "./Footer/Footer";
